disabled_rules:
  - function_parameter_count
  - nesting
  - variable_name
  - identifier_name
  - trailing_whitespace # XCode autoformatting add whitespace at empty lines
  - vertical_whitespace
  - type_body_length

opt_in_rules:
  - empty_count
  - private_outlet

excluded:
  - Carthage
  - Pods

line_length:
  ignores_comments: true
  warning: 250
  error: 300

function_parameter_count:
  warning: 10
  error: 15

function_body_length: 1000
